### ISSUE TITLE
If i use AuditScope.CreateAndSaveAsync and setup             Audit.Core.Configuration.JsonSettings = new JsonSerializerSettings()             {                 ReferenceLoopHandling = ReferenceLoopHandling.Ignore              };, I still get an error

### ISSUE THREAD

**Issue by vadim-bondaruk** [thepirat000/Audit.NET#126]

**Comment by thepirat000** [comment]
What data provider do you use (Audit.Core.Configuration.DataProvider)?

**Comment by thepirat000** [comment]
This is fixed on version 12.1.2

Note the `FileDataProvider` will **not** use the global settings from `Audit.Core.Configuration.JsonSettings`, but its own settings. Anyway they are now exposed via the `JsonSettings` property on `FileDataProvider`.

For example:
```
Configuration.DataProvider = new FileDataProvider() 
{ 
    JsonSettings = new JsonSerializerSettings { ReferenceLoopHandling = ReferenceLoopHandling.Ignore }
};
```

**Comment by vadim-bondaruk** [comment]
I am using AzureDbProvider and after update version to 12.1.2 still have this problem.
```
            Audit.Core.Configuration.JsonSettings = new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore

            };
            Configuration.DataProvider = new Audit.AzureDocumentDB.Providers.AzureDbDataProvider()
            {
                ConnectionString = configuration["CosmosDB:AccountEndpoint"],
                AuthKey = configuration["CosmosDB:AccountKey"],
                Database = configuration["CosmosDB:Datababase"],
                Collection = "ErrorLogs",

            };


await Audit.Core.AuditScope.CreateAndSaveAsync("Error", new { Exception = exception });
```

**Comment by thepirat000** [comment]
This is fixed on version 12.1.3.
AzureDocumentDB was not respecting the globally configured JsonSettings.

Please update and re-test
