### ISSUE TITLE
Typo in docs regarding adding Audit.EntityFramework without inheritance?

### ISSUE THREAD

**Issue by Shaddix** [thepirat000/Audit.NET#451]
https://github.com/thepirat000/Audit.NET/tree/master/src/Audit.EntityFramework#without-inheritance

There's the following code
```csharp
public class MyContext : DbContext
{
    private static DbContextHelper _helper = new DbContextHelper();
    private readonly IAuditDbContext _auditContext;
```
I believe that `static` shall not be there, since in `AuditIdentityDbContext` it's not static.
And personally I had issues with Audit.NET EFCore in multi-threading environments with DbContextHelper being defined as static.

Am I wrong, or is it really a typo in a Readme?

**Comment by thepirat000** [comment]
I think it could be either static or not, since internally the DbContextHelper handles static Concurrent Dictionaries

But do you have more information on how to reproduce the multi-threading issue you had?

**Comment by Shaddix** [comment]
I could prepare a minimal repro, yep

**Comment by thepirat000** [comment]
I've updated the readme to use an instance field instead, so you could go with that, but anyway I would like to reproduce the issue if it's possible.

**Comment by Shaddix** [comment]
Oh, seems like I was too fast to say that using an instance field instead of static gives no issues.. there's still an issue, though with a bit lower probability.

Anyway, here's the repo with repro:
https://github.com/Shaddix/AuditNetMultiThreadingRepro

if you request `GET /product` in parallel (e.g. via postman), the first request succeeds, the second one hangs trying to insert a lot of audit entries.
![image](https://user-images.githubusercontent.com/1249513/132139014-e7ba40e0-f255-4cd9-85e2-6afd6a1b9ce8.png)

The idea is that there's a transaction which is retried if there's a transient failure. And in case of 2 parallel requests it will indeed be retried, which causes an issue.
Maybe the way I'm using Audit.Net is wrong (in which case it'd be great if you tell me where I'm wrong).

**Comment by thepirat000** [comment]
How do you run the parallel requests? are you using Newman with Postman?

**Comment by thepirat000** [comment]
Nevermind my previous message, I was able to reproduce.

Please check this https://github.com/thepirat000/Audit.NET/issues/168#issuecomment-425609685

And try by using a different DbContext instance for the audits

**Comment by Shaddix** [comment]
Thanks!
That works, but then I have the same issue as in https://github.com/thepirat000/Audit.NET/issues/168#issuecomment-502372630 (in my example I had 6 audit log entries, while only 4 products, so it seems that rolled back transaction still got it AuditLog entries saved).

I tried to apply the solution from the aforementioned comment
```csharp
                .WithCreationPolicy(EventCreationPolicy.Manual)
                .WithAction(a => a
                    .OnEventSaving(scope =>
                    {
                        if (scope.Event.Environment.Exception != null)
                        {
                            scope.Discard();
                        }
                    })
```
which reduced the number of AuditLog entries to 5 instead of 6, but it's still one more than there should be.

I guess I should do something like you describe in [Overrides](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#overrides) section, but from the first sight it seems that I'll loose the event conversion from AuditEntityAction.

Am I right, that there's no other way to persist AuditLog entries in the same transaction as the main DbContext?

**Comment by thepirat000** [comment]
oh, I see. You want the audits on the same transaction.

One thing first, make sure you are excluding the `AuditLogEntry` entities from the audits, for example by decorating the class with `[AuditIgnore]`:

```c#
[AuditIgnore]
public class AuditLogEntry
{
  //...
}
```

The only way to reuse the transaction between different DbContext instances is to set the `DbConnection` and `DbTransaction` when creating the DbContext for auditing.

1. Change your DbContext constructor to use a custom audit context, instead of the DefaultAuditContext:

```c#
public MyDbContext(DbContextOptions<MyDbContext> options) : base(options)
{
    _auditContext = new TransactionalAuditContext(this);
    _helper.SetConfig(_auditContext);
}
```

2. Override `OnScopeCreated` method on the custom audit context, to store a reference of the Connection and the Transaction on the current audit event:

```c#
public class TransactionalAuditContext : DefaultAuditContext
{
    public TransactionalAuditContext(DbContext context) : base(context) { }
    public override void OnScopeCreated(IAuditScope auditScope)
    {
        var db = auditScope.GetEntityFrameworkEvent().GetDbContext().Database;
        auditScope.SetCustomField("DbConnection", db.GetDbConnection());
        auditScope.SetCustomField("DbTransaction", db.CurrentTransaction);
    }
}
```

> This should be easier if you are able to change the inheritance of your DbContext to AuditDbContext

3. Set the Connection and Transaction when creating the DbContext for the audits. On your startup:

```c#
private void ConfigureAudit(IServiceCollection services)
{
    Audit.Core.Configuration.Setup()
        .UseEntityFramework(config => config
            .UseDbContext(ev => 
            {
                var conn = (ev.CustomFields["DbConnection"] as DbConnection);
                var tran = (ev.CustomFields["DbTransaction"] as IDbContextTransaction);
                var auditContext = new MyDbContext(new DbContextOptionsBuilder<MyDbContext>().UseNpgsql(conn).Options);
                auditContext.Database.UseTransaction(tran.GetDbTransaction());
                return auditContext;
            })
            .AuditTypeMapper(...);
}
```

Please re-test with the suggested approach. I will check if it's feasible to provide this mechanism with a new setting on the EF Data Provider directly. Like a `MatchTransaction` boolean value to indicate if the connection and transaction should be shared in case of different DbContext instances.

**Comment by thepirat000** [comment]
oh, I see. You want the audits on the same transaction.

One thing first, make sure you are excluding the `AuditLogEntry` entities from the audits, for example by decorating the class with `[AuditIgnore]`:

```c#
[AuditIgnore]
public class AuditLogEntry
{
  //...
}
```

The only way to reuse the transaction between different DbContext instances is to set the `DbConnection` and `DbTransaction` when creating the DbContext for auditing.

So, you can set the Connection and Transaction when creating the DbContext for the audits. For example, in your startup:

```c#
private void ConfigureAudit(IServiceCollection services)
{
    Audit.Core.Configuration.Setup()
        .UseEntityFramework(config => config
            .UseDbContext(ev => 
            {
                var db = ev.EntityFrameworkEvent.GetDbContext().Database;
                var conn = db.GetDbConnection();
                var tran = db.CurrentTransaction;
                var auditContext = new MyDbContext(new DbContextOptionsBuilder<MyDbContext>().UseNpgsql(conn).Options);
                auditContext.Database.UseTransaction(tran.GetDbTransaction());
                return auditContext;
            })
            .AuditTypeMapper(x => x == typeof(AuditLogEntry) ? null : typeof(AuditLogEntry))
            .AuditEntityAction<AuditLogEntry>((ev, entry, auditLog) => { })
            .IgnoreMatchedProperties(true));
}
```

Please re-test with the suggested approach. I will check if it's feasible to provide this mechanism with a new setting on the EF Data Provider directly. Like a `MatchTransaction` boolean value to indicate if the connection and transaction should be shared in case of different DbContext instances.

**Comment by Shaddix** [comment]
Thanks, it works!
I also agree that having a `MatchTransaction` configuration option would significantly simplify things :)

Thanks for your efforts put in the library and extremely quick responses!
