### ISSUE TITLE
SaveChangesAsync fails with Audit.EntityFrameworkCore when a property is mapped to JSON

### ISSUE THREAD

**Issue by mcjeffery** [thepirat000/Audit.NET#555]
**Describe the bug**
When the model contains properties that are owned entities mapped to JSON columns, an ArgumentNullReference exception is thrown.

  Message: 
System.ArgumentNullException : Value cannot be null. (Parameter 'key')

  Stack Trace: 
Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
DbContextHelper.GetColumnValues(IAuditDbContext context, EntityEntry entry)
DbContextHelper.CreateAuditEvent(IAuditDbContext context)
DbContextHelper.SaveChangesGetAuditAsyncImpl(IAuditDbContext context, Func`1 baseSaveChanges)
DbContextHelper.SaveChangesAsync(IAuditDbContext context, Func`1 baseSaveChanges)
AuditDbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

**To Reproduce**
Create a model with a property that is an owned entity which is mapped to a JSON column using the .ToJson() method in model builder. Then add the model using DbSet.Add and call SaveChangesAsync.

(Extra code removed for brevity.)

public class TestParent
{
    public TestChild  ChildEntity { get; set; }
}

public  class TestChild
{
    public string Name { get; set; }
}

public class TestContext : AuditDbContext
{
    public override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TestParent>().OwnsOne(e => e.ChildEntity, a => a.ToJson());
    }
}

**Expected behavior**
No exception should be thrown.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.Net: 20.1.1
 - Audit.EntityFrameworkCore: 20.1.1

**Target .NET framework:**
For example:
 - .NET 6
 - Entity Framework Core 7

**Additional context**
The problem appears to be caused because prop.GetColumnName(storeObjectIdentifier.Value) in DbContextHelper.GetColumnName returns null for properties that are mapped to JSON columns. In the code I worked with, if I called prop.GetDefaultColumnBaseName() when storeObjectIdentifier.HasValue is false (existing codebase) OR when prop.DeclaringEntityType.IsMappedToJson() is true (my additional logic), the exception went away.

**Comment by thepirat000** [comment]
This was fixed in version 20.1.2, please upgrade your references and re-test

**Comment by mcjeffery** [comment]
The 20.1.2 version seems to have fixed the issue.

**Comment by JEkedorff** [comment]
Anyone else still experiences the same problem?
I get the exact same fault in version 20.1.4. Have tested to downgrade to 20.1.2 but with same result.

**Comment by mcjeffery** [comment]
I found that the fix only works with .Net 7. It still fails with lower .Net versions.

**Comment by JEkedorff** [comment]
Okay, that explains it. 👍My project runs .NET 6.
Any idea whether it is fixable for or is .NET 7 required for JSON mapping support?
Thanks for a quick response and a great lib!

**Comment by thepirat000** [comment]
The problem is that the library assumes EF Core 6 when targeting .NET 6.0.

https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.EntityFramework/README.md#ef-library-version

I think it can be upgraded to target EF Core 7 for .NET 6.0, but it will break backward compatibility for anyone using EF Core 6
